compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@antfu/eslint-config@*":
    dependencies:
      "@typescript-eslint/utils": "*"
      "@vue/compiler-sfc": "*"
      typescript: "*"
  "@floating-ui/vue@*":
    peerDependencies:
      vue: "*"
  "@stylistic/eslint-plugin@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
      typescript: "*"
  "@typescript-eslint/eslint-plugin@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
  "@vitest/eslint-plugin@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
  eslint-plugin-n@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
      typescript: "*"
  eslint-plugin-perfectionist@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
      typescript: "*"
  "@nuxt/icon@*":
    peerDependencies:
      vite: "*"
      vue: "*"
  "@nuxt/fonts@*":
    peerDependencies:
      vite: "*"
  "@regle/rules@*":
    peerDependencies:
      vue: "*"
  "@nuxt/ui@*":
    peerDependencies:
      vite: "*"
      vue: "*"
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
