// @ts-check
import antfu from '@antfu/eslint-config'
// import EslintAutoImport from './types/js/autogenerated/eslintrc-auto-import.js'

export default antfu({
    unocss: false,

    javascript: {
        overrides: {
            'antfu/no-top-level-await': 'off',
        },
    },

    vue: {
        overrides: {
            'vue/script-indent': ['error', 4, {
                baseIndent: 1,
                switchCase: 1,
            }],

            'vue/html-indent': ['error', 4, {
                attribute: 1,
                alignAttributesVertically: true,
            }],

            'vue/component-name-in-template-casing': ['error', 'kebab-case', {
                registeredComponentsOnly: false,
            }],

            'vue/custom-event-name-casing': ['error', 'kebab-case', {
                ignores: [
                    '/^[a-z]+(?:-[a-z]+)*:[a-z]+(?:-[a-z]+)*$/u',
                ],
            }],

            'vue/singleline-html-element-content-newline': 'off',
        },
    },

    typescript: {
        // tsconfigPath: 'tsconfig.json',

        overrides: {
            'ts/no-unused-expressions': ['error', { allowTernary: true }],
        },
    },

    yaml: {
        overrides: {
            'yaml/indent': ['error', 2],

            'yaml/quotes': ['error', {
                prefer: 'double',
            }],
        },
    },

    stylistic: {
        indent: 4,
        quotes: 'single',
        overrides: {
            'style/indent': 'off',
            'style/brace-style': ['error', '1tbs'],
        },
    },

    ignores: [
        './electron-builder.mjs',
        '.github/**',
        '.yarn/**',
        'node_modules/**',
        'vendor/**',
        'lang/**',
        'public/build/**',
        'public/dist/**',
        'public/vendor/**',
        'types/js/autogenerated/**/*',
        'types/autogenerated/**/*',
        'dist',
    ],
}, {
    // languageOptions: EslintAutoImport,
})
