name: Setup boilerplate

runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        Xvfb :99 -screen 0 1280x960x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: yarn

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: yarn-${{ runner.os }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          yarn-${{ runner.os }}-

    - name: Install Dependencies
      run: yarn install --immutable
      shell: bash
