# This file serves as a boilerplate template rather than an end-application script.

name: Build application for deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check-version-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-version.outputs.version }}
      tag-exists: ${{ steps.check-tag.outputs.exists }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from package.json
        id: read-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version tag exists
        id: check-tag
        run: |
          VERSION=${{ steps.read-version.outputs.version }}
          if git ls-remote --exit-code --tags origin "refs/tags/v$VERSION"; then
            echo "Version tag v$VERSION exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version tag v$VERSION does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT

  run-ci-for-template:
    name: ci.yml
    needs: check-version-tag
    if: needs.check-version-tag.outputs.tag-exists == 'false'
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: 'release'
    permissions:
      contents: write
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
