# This file serves as a boilerplate template rather than an end-application script.

name: Build application for deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run-ci-for-template:
    name: ci.yml
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: 'release'
    permissions:
      contents: write
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
